### ISSUE TITLE
UI/UX Implementation

### ISSUE THREAD

**Issue by RingComics** [RingComics/ultskylauncher#5]

**Comment by RingComics** [comment]
[Figma page](https://www.figma.com/file/TIPfb8ce8fwWGVlqgOFemP/UltSkyLauncher_v2?node-id=32842%3A310896)

**Comment by MattLish** [comment]
@JU12000 @RingComics @phinocio Should we consider this complete now? The UX looks to have bee fully implemented.
Anything additional can have it's own issue/item in the project?

I will close for now, please shout if you disagree.
